### ISSUE TITLE
Do we need any other dependency to run the project?

### ISSUE THREAD

**Issue by palmanza** [papmodern/drawer3d#1]
Hi, just wanted to try and help you find a way to make a better initial transition/shadow, the thing is I can't seem to make the drawer3d app to work on my emulator, im on windows on vscode, do I need any other dependency to make it work?

**Comment by papmodern** [comment]
Hello. Sorry for delayed response. 
No everything you need is packed inside the repository.
Can you exactly tell me the errors you faced?

**Comment by palmanza** [comment]
I was able to make it work, I just needed some configuration on my end. Pretty neat tho.
